### ISSUE TITLE
weird repo

### ISSUE THREAD

**Issue by sh0tx420** [SmellyFishRW/Nuclear-Energy#1]
issue: repo is weird
what is this supposed to achieve

**Comment by SmellyFishRW** [comment]
It's just a nonsteam download of my mod lol
https://steamcommunity.com/sharedfiles/filedetails/?id=1586735724

Everyone in the rimworld community posts the nonsteam downloads of their mods on github

**Comment by MBR-0001** [comment]
![](https://cdn.discordapp.com/emojis/794004570299695144.png)
